#define VER_SHORTPRODUCTNAME_STR_PS "Virtuozzo"
#define VER_COMPANYNAME_STR "Virtuozzo International GmbH"
#define VER_COMPANYNAME_REGISTRYBRANCH_STR "Virtuozzo"
#define VER_LEGALTRADEMARKS_STR "Virtuozzo is a trademark of " VER_COMPANYNAME_STR
#define VER_WEBSITE_STR "virtuozzo.com"
#define PRL_PRODUCT_NAME_SERVER "Virtuozzo Server"
#define PRL_VENDOR "Virtuozzo"
#define PRL_VENDOR_URL "virtuozzo.com"
